project:
  type: book

book:
  title: "Manual for Dr. Hu's Amazing Team"
  author: "胡悦"
  date: today
  chapters:
    - index.qmd
    - markdown.qmd
    - bookdown.qmd
    - zotero.qmd
    - lit.qmd
    - git.qmd

bibliography: references.bib
highlight-style: github
number-sections: true
toc: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    echo: true
    message: true
    warning: true
    dpi: 300

format:
  html:
    theme:
        light: simplex
        dark: slate
  docx: default
    
    



