project:
  type: book

book:
  title: "Open Manual for Dr. Hu's Amazing Team"
  author: "胡悦"
  date: today

  chapters:
    - index.qmd
    - zotero.qmd
    - lit.qmd
    - naming.qmd

bibliography: references.bib
highlight-style: github
number-sections: true
toc: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    echo: true
    message: true
    warning: true
    # dpi: 300

format:
  html:
    cover-image: images/drhutools.png
    theme:
        light: lux
        dark: cyborg
    css: style_custom.css
  docx: default
    



